version: 0.2

phases:
  install:
    commands:
      - echo Installing node modules...
      - npm install --production
  build:
    commands:
      - echo Building application...
      - npm run build
  post_build:
    commands:
      - npm run test

artifacts:
  files:
    - '**/*'